Add first version of install script and add help menu.

diff --git a/bin/tscc b/bin/tscc
--- a/bin/tscc
+++ b/bin/tscc
@@ -6,8 +6,18 @@ source "$(realpath $(dirname $(realpath "${BASH_SOURCE[0]}"))/../)/tscc.env"
 # Ensure environment
 #
 
+tscc_error() {
+	echo "ERROR: $1" 1>&2
+	exit 1
+}
+
+if ! command -v curl >/dev/null; then
+	tscc_error "curl is required to use tscc."
+	exit 1
+fi
+
 if ! command -v jq >/dev/null; then
-	echo "Error: jq is required to use tscc." 1>&2
+	tscc_error "jq is required to use tscc."
 	exit 1
 fi
 
@@ -17,7 +27,7 @@ fi
 
 tscc_download() {
   echo "Downloading ${1}..."
-	wget -qO "$2" "$1"
+	curl -fsSL -o "$2" "$1"
 }
 
 tscc_ensureNode() {
@@ -25,8 +35,7 @@ tscc_ensureNode() {
 		cd $(mktemp -d)
     local downloadUrl="https://nodejs.org/dist/v${TSCC_NODE_VERSION}/${TSCC_NODE_IDENTIFIER}-${TSCC_PLATFORM}.tar.gz"
     if ! tscc_download "${downloadUrl}" "node.tar.gz"; then
-      echo "Failed to download node from \"${downloadUrl}\""
-      exit 1
+      tscc_error "Failed to download node from \"${downloadUrl}\""
     fi
     tar xzf "node.tar.gz"
     rm "node.tar.gz"
@@ -41,8 +50,7 @@ tscc_ensureTypeScript() {
 		cd $(mktemp -d)
     local downloadUrl="https://github.com/microsoft/TypeScript/releases/download/v${TSCC_TYPESCRIPT_VERSION}/typescript-${TSCC_TYPESCRIPT_VERSION}.tgz"
     if ! tscc_download "${downloadUrl}" "typescript.tgz"; then
-      echo "Failed to download TypeScript from \"${downloadUrl}\""
-      exit 1
+      tscc_error "Failed to download TypeScript from \"${downloadUrl}\""
     fi
     tar xzf "typescript.tgz"		
     rm "typescript.tgz"
@@ -56,8 +64,7 @@ tscc_ensureESBuild() {
 		cd $(mktemp -d)
     local downloadUrl="https://esbuild.github.io/dl/v${TSCC_ESBUILD_VERSION}"
     if ! tscc_download "${downloadUrl}" "esbuild.sh"; then
-      echo "Failed to download esbuild from \"${downloadUrl}\""
-      exit 1
+      tscc_error "Failed to download esbuild from \"${downloadUrl}\""
     fi
     sh "esbuild.sh"
     mv "esbuild" "${TSCC_ESBUILD_PATH}"
@@ -85,6 +92,41 @@ TSCC_TSC_FLAGS="-p ${TSCC_TMP_PATH}/tsconfig.json"
 TSCC_ESBUILD_FLAGS="--bundle --format=esm --jsx=automatic"
 TSCC_ESBUILD_OUTFILE=""
 
+tscc_printHelpAndExit() {
+	echo "
+Usage:
+	tscc [options] [entry points]
+
+Repository:
+	https://github.com/smack0007/tscc
+
+Options:
+  
+	-h, --help
+    Print help.
+	--init
+		Writes initiali tsconfig.json files for project setup.
+	--jsx
+		Set compilerOptions.jsx for tsc. 
+  --jsxFactory
+		Set compilerOptions.jsxFactory for tsc.
+	--jsxFragmentFactory
+		Set compilerOptions.jsxFragmentFactory for tsc.
+	--minify
+		Pass minify flag to esbuild.
+	-o, --output
+		Set the output file for esbuild.
+	--path [name]:[path]
+		Add an entry to compilerOptions.paths for tsc.
+	--sourcemap
+		Pass sourcemap flag to esbuild.
+	--version
+		Print version information and exit.
+"
+	echo "Note: Deno was not installed"
+	exit 0
+}
+
 tscc_writeTsConfig() {
 	TSCC_TSCONFIG="// This file was generated by tscc.
 ${TSCC_TSCONFIG}
@@ -102,8 +144,8 @@ tscc_invokeESBuild() {
 
 while [[ $# -gt 0 ]]; do
   case $1 in
-    --help)
-			exit 0
+    -h|--help)
+			tscc_printHelpAndExit
 			;;
 		
 		--init)
